### ISSUE TITLE
No command to remove old / unused snapshot

### ISSUE THREAD

**Issue by wyatt-wong** [samkusin/clemens_iigs#105]
I have created 2 snapshots but when I try to load the snapshot, I found that there are no commands to remove the old snapshots.

<img width="1552" alt="Screenshot 2023-04-09 at 2 13 25 AM" src="https://user-images.githubusercontent.com/10095648/230736747-e9a009e6-c0fc-42fe-810d-d060eb5225f1.png">

**Comment by samkusin** [comment]
For now you can select the folder icon at the bottom of the screen by the 'bug' and delete snapshots manually.

Most of these options will be moved to a menu bar at some point.

**Comment by wyatt-wong** [comment]
> For now you can select the folder icon at the bottom of the screen by the 'bug' and delete snapshots manually.
> 
> Most of these options will be moved to a menu bar at some point. Though a delete option in the browser is probably a good option for this case.

I found out the location of the snapshot which I can manually deleted it from macOS Finder.
