### ISSUE TITLE
Remember the previous path for "Import master" disk image

### ISSUE THREAD

**Issue by wyatt-wong** [samkusin/clemens_iigs#107]
The "import master" disk image function should remembered the path of the previous disk image. If I put all disk images in a certain path such as /Users/<username>/GS Disks/, then the "import master" should show this folder for me when I need to select the next image.

Currently, the "import master" always default to / folder which is very annoying.

But of course I don't personally prefer to have "import master" function. The user should be able to choose any disk images without the need to "import" it to a folder. So far I did not see AppleWin, Virtual ][ or any IIGS emulator that require the use of "import master" function.

**Comment by samkusin** [comment]
Fixed by #111
