### ISSUE TITLE
Failed to load the "Where in the World is Carmen Sandiego" IIGS game

### ISSUE THREAD

**Issue by wyatt-wong** [samkusin/clemens_iigs#108]
I download the "Where in the World is Carmen Sandiego" IIGS game from the 4am collection below.

[https://archive.org/details/wozaday_Where_in_the_World_is_Carmen_Sandiego_IIgs](url)

I imported disk 1 into S5,D1 and disk 2 into S5,D2, then reboot the IIGS emulator. After the IIGS GUI have successfully loaded, I double clicked "Carmen.World" to start the game

<img width="1440" alt="Screenshot 2023-04-10 at 10 50 05 PM" src="https://user-images.githubusercontent.com/10095648/230927806-32a193d4-5d55-468e-8e66-06cefb9cbf17.png">

<img width="1440" alt="Screenshot 2023-04-10 at 10 50 21 PM" src="https://user-images.githubusercontent.com/10095648/230927942-bce1448b-4d74-46a5-8d32-7bdde754f448.png">

After the Borderbund Logo showed up, I clicked on the screen to bypass the splash screen but then I got a dialog box of "Insert original Carmen.World2". However, the "Where in the World is Carmen Sandiego" disk 2 is already inserted into the S5,D2

<img width="1440" alt="Screenshot 2023-04-10 at 10 51 02 PM" src="https://user-images.githubusercontent.com/10095648/230928187-bd353552-5459-406d-97a2-3c2028df4a25.png">

I clicked the Play button in the following URL and performed the above steps, I was able to see the game was successfully loaded without problems. So it looks like the problem is in the IIGS emulator itself.

[https://archive.org/details/wozaday_Where_in_the_World_is_Carmen_Sandiego_IIgs](url)

I have included the screenshots below:

<img width="1440" alt="Screenshot 2023-04-10 at 11 08 34 PM" src="https://user-images.githubusercontent.com/10095648/230929564-dce8bbfa-dd36-4ad8-a54c-3c004c77e858.png">

<img width="1440" alt="Screenshot 2023-04-10 at 11 08 43 PM" src="https://user-images.githubusercontent.com/10095648/230929590-127238a9-ab6a-4ae4-8cd3-6f0f68030f83.png">

<img width="1440" alt="Screenshot 2023-04-10 at 11 09 05 PM" src="https://user-images.githubusercontent.com/10095648/230929608-7ab04746-ce51-4ebb-8b0c-789b1650fbe7.png">

<img width="1440" alt="Screenshot 2023-04-10 at 11 09 32 PM" src="https://user-images.githubusercontent.com/10095648/230929626-73135d0a-022b-4871-9481-2a3724caacfe.png">

<img width="1440" alt="Screenshot 2023-04-10 at 11 09 49 PM" src="https://user-images.githubusercontent.com/10095648/230929646-ceb39ea6-1ba2-4d70-a40c-0f8cb0a2a394.png">

**Comment by samkusin** [comment]
This was due to the disk emulator's 3.5" read timings being slightly off - which would only manifest as a result of the copy protection scheme used by the IIgs version of Carmen Sandiego (tracks 20,21 side 1 for future reference.)

This has been fixed by PR #132 .
