### ISSUE TITLE
Unable to startup System 6.0.4

### ISSUE THREAD

**Issue by wyatt-wong** [samkusin/clemens_iigs#96]
I build it from the source and start it under macOS Catalina:

<img width="1552" alt="1" src="https://user-images.githubusercontent.com/10095648/230246939-02218608-2f0f-4e79-97c9-0ceb9e294d92.png">

<img width="1552" alt="2" src="https://user-images.githubusercontent.com/10095648/230247092-5568a7f1-e93d-420d-b5c8-683654eb7ea7.png">

1. I clicked on S6, D1 and choose \<import master\>

<img width="1552" alt="3" src="https://user-images.githubusercontent.com/10095648/230247634-20a7f199-85c4-489e-b052-483ecccacfdd.png">

2. I choose the folder where System 6.0.4 was located:

<img width="1552" alt="4" src="https://user-images.githubusercontent.com/10095648/230247256-870ce3ef-3f14-4aeb-8eae-fcc626364d05.png">

3. I clicked the OK button

<img width="1552" alt="5" src="https://user-images.githubusercontent.com/10095648/230247371-7a302c62-90e3-4b83-be69-c468b6b4fcbd.png">

4. I got the dialog box of "Select Destination". When I clicked on "Create Directory", there is no response. If I click Cancel, the import master operation will fail

<img width="1552" alt="6" src="https://user-images.githubusercontent.com/10095648/230247450-ceef81fe-edf5-4203-9824-314883d1862b.png">

**Comment by samkusin** [comment]
There is a text inputbox next to Create Directory that if you click should allow you to name a directory.  Then click create.   

Perhaps a dialog should come up or the option should be grayed.  Alternately if there are no directories then the GUI should not show an empty list and automatically select the input box.

I can also create some initial directories so there's always something available.  Anyway the instructions in the first paragraph above should get you passed that.

**Comment by samkusin** [comment]
Also if you are selecting an 800K image, that is a 3.5" disk which should go in slot 5.

I will rename these entries to say "3.5 inch drive" or something like that.

A good longer term solution to help those that aren't familiar with the various disk image and drive hardware would be for the browser to display the disk type.

**Comment by wyatt-wong** [comment]
> Also if you are selecting an 800K image, that is a 3.5" disk which should go in slot 5 versus slot 6. After creating a directory you would likely be greeted with an error about the image not being a 5.25 inch disk image (140k).
> 
> I will rename these entries to say "3.5 inch drive" or something like that. The traditional Apple IIgs slot assignments for these drives are reflected in the GUI but the interface should be friendlier.
> 
> A good longer term solution to help those that aren't familiar with the various disk image and drive hardware would be for the browser to display the disk types and filter for what's allowed.

OK. I understand more how to select the disk and create the directory. But even after I selected System.Disk in S5,D1 and I clicked Reboot (cycle power), I cannot see the System 6.0.4 boot up.

**Comment by wyatt-wong** [comment]
> > Also if you are selecting an 800K image, that is a 3.5" disk which should go in slot 5 versus slot 6. After creating a directory you would likely be greeted with an error about the image not being a 5.25 inch disk image (140k).
> > I will rename these entries to say "3.5 inch drive" or something like that. The traditional Apple IIgs slot assignments for these drives are reflected in the GUI but the interface should be friendlier.
> > A good longer term solution to help those that aren't familiar with the various disk image and drive hardware would be for the browser to display the disk types and filter for what's allowed.
> 
> OK. I understand more how to select the disk and create the directory. But even after I selected System.Disk in S5,D1 and I clicked Reboot (cycle power), I cannot see the System 6.0.4 boot up.

OK. I fixed the problems after I found the CORRECT Apple IIGS ROM3 file and now I can successfully boot up the IIGS. It looks like the UI is not intuitive enough for novice users like myself to use it.

**Comment by samkusin** [comment]
ROM validation is a good feature to detect valid IIGS ROM files (there are obvious signature bytes in the binary file.)    

This will be necessary when ROM 1 support is added (and to help avoid bad ROM files from messing things up.)

**Comment by samkusin** [comment]
Links:
#55 
#39

**Comment by samkusin** [comment]
I'll add links to other IIGS emulators if you want to try them out.   They vary in end-user experience (AMPLE has more of a GUI vs KEGS.)    KEGS probably has the best IIGS feature support.   AMPLE, uses a MAME backend which has had a lot of iteration.

https://github.com/ksherlock/ample
https://kegs.sourceforge.net/
