### ISSUE TITLE
How to exit from the Debugger view ?

### ISSUE THREAD

**Issue by wyatt-wong** [samkusin/clemens_iigs#98]
How do I exit from the Debugger View ?

**Comment by samkusin** [comment]
type `minimode` into the input box on the lower right of the screen.   Also I think there's a shortcut key:  Ctrl + Option + F11 on macOS.

**Comment by wyatt-wong** [comment]
> type `minimode` into the input box on the lower right of the screen. Also I think there's a shortcut key: Ctrl + Option + F11 on macOS.

This need to add into the documentation.

**Comment by samkusin** [comment]
You can click inside the box where there's a '*'.   That will enable the command prompt for the debugger.   From there type `minimode`.   You can also type `help` if you find yourself using the debugger. 

If you are on a Mac keyboard with a 'Fn' key, sometimes that is set up to turn the 'volume' key into a function key (at least on my macbook air.)   Basically all keys like volume up/down/mute/brightness have function key equivalents if you press 'Fn'.

**Comment by wyatt-wong** [comment]
> You can click inside the box where there's a '*'.   That will enable the command prompt for the debugger.   From there type `minimode`.   You can also type `help` if you find yourself using the debugger. 
> 
> 
> 
> If you are on a Mac keyboard with a 'Fn' key, sometimes that is set up to turn the 'volume' key into a function key (at least on my macbook air.)   Basically all keys like volume up/down/mute/brightness have function key equivalents if you press 'Fn'.

Would it be more user friendly to include a button to exit the Debugger View ? Or to include a menu item with shortcut key ? I can see the macOS menu was not utilized at all in the emulator.

**Comment by samkusin** [comment]
Use the debug button to toggle in and out.  Main menu option will also be adaded.
